baseURL = "http://data-handyman.com/"
languageCode = "en-us"
title = "Data Handyman"
theme = "minimal"
publishDir = "docs"
# disqusShortname = "data-handyman" # delete this to disable disqus comments

[params]
    author = "Liam Cryan"
    description = "Finally, a handyman for...data"
    githubUsername = "liamcryan"
    accent = "brown"
    showBorder = true
    backgroundColor = "beige"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:liam@data-handyman.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/liamcryan/"
    name = "github"
    weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/liam-cryan-8a1a4853/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
